version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: roman-numerals-backend
    ports:
      - "8081:3000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: http://localhost:8081
    container_name: roman-numerals-frontend
    ports:
      - "8082:80"
    depends_on:
      - backend
